### ISSUE TITLE
Error setting the private key for deployer

### ISSUE THREAD

**Issue by jsidorenko** [wighawag/hardhat-deploy#60] opened 2020-12-08 11:10 UTC
According to documentation, it's possible to pass the private key in the `from` field of the `deploy` method.
When doing so, I'm getting that error from ethers.js: ```Error: missing provider (operation="estimateGas", code=UNSUPPORTED_OPERATION, version=abstract-signer/5.0.5)```
I think you need to additionally pass the provider here https://github.com/wighawag/hardhat-deploy/blob/master/src/helpers.ts#L940

P. S. Maybe there are more ways to set the private key that is gonna be used for contracts deployment to non-local networks?
I found the only option is to pass that private key with the `from` param

**Comment by wighawag** [comment] 2020-12-08 13:37
thanks for the report. it seems to that the issue is indeed that I do not pass the provider. Need to be fixed.

Re deployment with account
What I do usually is using a specific mnemonic for live network, see : https://github.com/wighawag/template-ethereum-contracts/blob/main/.env.example

**Comment by jsidorenko** [comment] 2020-12-08 14:12
Thanks!
I just noticed that for non-hardhat networks you should pass the private key as `const accounts = [privateKey]` while for the hardhat network it will be: `const accounts = [{ privateKey, balance }]`

**Comment by wighawag** [comment] 2021-01-06 09:24
It should be fixed now

**Closed by wighawag** 2021-01-06 09:24 UTC
Labels: bug
