### ISSUE TITLE
inline href # links don't work in readme (missing _)

### ISSUE THREAD

**Issue by jrfrantz** [wighawag/hardhat-deploy#186] opened 2021-09-08 20:46 UTC
Inline links don't work on the hardhat.org website for this plugin.

For example, if you click [3. hardhat test] it links to #3-hardhat-test but stays in place. When you scroll down to that section, you'll notice that it's hyperlinked with an underscore (#_3-hardhat-test).

Recommended fix: prepend underscores inline

**Comment by wighawag** [comment] 2021-09-09 08:28
this is a bug on hardhat.org website : https://github.com/nomiclabs/hardhat/issues/1800

I ll close this issue as it also a duplicate of : https://github.com/wighawag/hardhat-deploy/issues/161

**Closed by wighawag** 2021-09-09 08:28 UTC
