### ISSUE TITLE
Proxy contracts NEED to have some kind of validation

### ISSUE THREAD

**Issue by Dylan-Kerler** [wighawag/hardhat-deploy#141] opened 2021-06-24 17:00 UTC
At the moment if you try to deploy a proxy contract with an implementation that has invalid structure it will still succeed.
For example this contract will deploy fine:

```solidity
contract Foo {
  uint public b;
  uint public c = 5;

  constructor(a uint) { 
    b = a; 
  }
}
```

But this contract is invalid when deployed from a proxy. Because any proxy relaying to this implementation won't have the `c` or `b` variables set. I think it should throw an error here if the user tries to deploy this or at least some kind of warning.

**Comment by Dylan-Kerler** [comment] 2021-06-24 17:12
Also related, is in upgrading proxies - Storage collisions cause non-trivial errors. Obviously, it's harder to verify this because an upgrade could happen at a distant point in the future.

Old implementation:
```solidity
contract Foo { 
  uint public b = 5;
};
```

New implementation:
```solidity
// Incorrect
contract Bar { 
  uint public c; // Collision here! - value is actually set to 5 not 0
}

// Correct
contract Bar {
  uint public b; // value is 5 as expected
  uint public c; // value is 0
}
```

But it would be useful to have a function that checks that the new contract doesn't conflict with the old contracts storage.

`const isValid = deployments.isValidProxyUpgrade(oldContractArtifact, newContractArtifact);`

OpenZeppelin has a similar check but it is in-built into their deploy function so is of no use here in hardhat-deploy.

**Comment by wighawag** [comment] 2021-08-17 13:36
Definitely wanted :), this was also mentioned here : https://github.com/wighawag/hardhat-deploy/issues/65

**Comment by wighawag** [comment] 2021-10-03 18:50
closing as duplicate of #65

**Closed by wighawag** 2021-10-03 18:50 UTC
