### ISSUE TITLE
[bug] statement in onPendingTx function is wrong

### ISSUE THREAD

**Issue by truong-vcc** [wighawag/hardhat-deploy#175] opened 2021-08-23 08:39 UTC
I got this error in version 0.8.11, not sure if later versions have this error. The current command will throw an exception when tx.raw is undefined

```javascript 
const decoded = tx.raw
        ? undefined
        : {
            from: tx.from,
            gasPrice: tx.gasPrice.toString(),
            gasLimit: tx.gasLimit.toString(),
            to: tx.to,
            value: tx.value.toString(),
            nonce: tx.nonce,
            data: tx.data,
            r: tx.r,
            s: tx.s,
            v: tx.v,
            // creates: tx.creates, // TODO test
            chainId: tx.chainId,
          };

**Comment by wighawag** [comment] 2021-08-23 08:43
Thanks for your report
Can you give me the full error and a bit more on the context,
with EIP-1559 there is an error (Fixed in hardhat-deploy@next) related to gasPrice since it can now be undefined, but what you post seems to be a different issue.
Any repo to reproduce it ?

**Comment by truong-vcc** [comment] 2021-08-23 08:46
I am trying to implement a smart contract of my own using your library. But somehow in the onPendingTx function, tx.raw is undefined and that statement throws an exception

**Comment by wighawag** [comment] 2021-08-23 08:52
Ok, this seems to be the same thing, this is not tx.raw which is undefined but tx.gasPrice (See the toString in the error)

try with hardhat-deploy@next

**Comment by truong-vcc** [comment] 2021-08-23 08:58
> Ok, this seems to be the same thing, this is not tx.raw which is undefined but tx.gasPrice (See the toString in the error)
> 
> try with hardhat-deploy@next

Oh, this works. Thanks for help

**Closed** 2021-08-23 08:59 UTC
