### ISSUE TITLE
Method initialize not found on upgradable contracts

### ISSUE THREAD

**Issue by clemsos** [wighawag/hardhat-deploy#122] opened 2021-06-10 13:04 UTC
Hello, I am moving my project from Ganache to Hardhat and have an existing Zeppelin contract `ERC20Detailed` with an `initialize` function. 

When I run the deployment task with a proxy pattern, I get: `Error: contract need to implement function initialize`. 

I have tried to either use the `methodName` param or another `execute` function (pretty much like shown in #118) but still no luck.

The `DiscountToken.sol` contract (is an old solidity version...)

```solidity
pragma solidity 0.5.17;

import '@openzeppelin/contracts-ethereum-package/contracts/token/ERC20/ERC20Mintable.sol';
import '@openzeppelin/contracts-ethereum-package/contracts/token/ERC20/ERC20Detailed.sol';

/**
* @title The Discount Token
* This smart contract implements the Discount Token
*/
contract DiscountToken is
ERC20Mintable,
ERC20Detailed
{
  /**
   * @notice A one-time call to configure the token.
   * @param _minter A wallet with permissions to mint tokens and/or add other minters.
   */
  function initialize(address _minter) public initializer()
  {
    ERC20Mintable.initialize(_minter);
    ERC20Detailed.initialize('Discount Token', 'UDT', 18);
  }
}
```

The deploy script

```js
module.exports = async ({
    getNamedAccounts,
    deployments
}) => {
    const { owner, minter, proxyAdmin } = await getNamedAccounts();
    const { deploy } = deployments;

    const dt = await deploy('DiscountToken', {
        from: owner,
        log: true,
        args: minter,
        proxy: {
            methodName: 'initialize',
            owner: proxyAdmin,
            proxyContract: 'OpenZeppelinTransparentProxy',
        }
    });

    console.log(`DT initialized at: ${dt.address}`)
}

module.exports.tags = ['DT'];
```

Any idea what I am doing wrong here?

Many thanks all the very useful work!

**Comment by playsnook** [comment] 2021-06-10 13:54
I think you don't use openzeppelin upgradable contracts. For v4 of OZ contracts, use
```
npm i -D @openzepplein/contracts-upgradable
```

instead of

```
npm i -D @openzepplein/contracts
```

and export as
```
import "@openzeppelin/contracts-upgradeable/proxy/utils/Initializable.sol";
```

**Comment by wighawag** [comment] 2021-06-10 16:32
@clemsos the args must be an array, not sure if it is the issue but maybe

**Comment by clemsos** [comment] 2021-06-11 08:03
thanks @wighawag . I made args an array but still the same error :/ 

@playsnook yep, I am migrating to the newer libs and solidity, but this appears not so straightforward. The contract is used on mainnet and there are potential storage conflicts that needs to be taken into account before making any changes. Why hardaht-deploy :)

I am deploying similar contracts locally and it works just fine.

Here is the error when using a 2nd tx to init with the same contract as above

```js
module.exports = async ({
    getNamedAccounts,
    deployments
}) => {
    const { owner, minter, proxyAdmin } = await getNamedAccounts();
    const { deploy, execute } = deployments;

    const dt = await deploy('DiscountToken', {
        from: owner,
        log: true,
        proxy: {
            owner: proxyAdmin,
            proxyContract: 'OpenZeppelinTransparentProxy',
        }
    });

    console.log(`DT initialized at: ${dt.address}`)

    await execute(
        'DiscountToken',
        { 
            from: owner,
            log: true
        },
        'initialize',
        minter
    )
}

module.exports.tags = ['DT'];
```

error log 

```sh
$ npx hardhat node                                                                                                                                                                  1 ↵
Nothing to compile
deploying "DefaultProxyAdmin" (tx: 0x4e2da49e632d83e4c48c1a51934ac36d62546f57c033c86dacb398522bc92d1e)...: deployed at 0x5FbDB2315678afecb367f032d93F642f64180aa3 with 671461 gas
deploying "DiscountToken_Implementation" (tx: 0x6bf935ba1cb0376ef5343edb9633b876e65f700d60596af02cc2f436dc10aa1f)...: deployed at 0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512 with 1830536 gas
deploying "DiscountToken_Proxy" (tx: 0x543f127af8fb0fdeb755bc1ab823bc81faaf54db161251b9471ea4914c8ae4de)...: deployed at 0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0 with 544341 gas
DT initialized at: 0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0
Error HH604: Error running JSON-RPC server: ERROR processing /Users/clemsos/Dev/unlock/hardhat-deploy-init/deploy/1_deploy_and execute.js:
Error: No method named "initialize" on contract deployed as "DiscountToken"
    at execute (/Users/clemsos/Dev/unlock/hardhat-deploy-init/node_modules/hardhat-deploy/src/helpers.ts:1804:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at runNextTicks (internal/process/task_queues.js:66:3)
    at listOnTimeout (internal/timers.js:518:9)
    at processTimers (internal/timers.js:492:7)
    at Object.module.exports [as func] (/Users/clemsos/Dev/unlock/hardhat-deploy-init/deploy/1_deploy_and execute.js:19:5)
    at DeploymentsManager.executeDeployScripts (/Users/clemsos/Dev/unlock/hardhat-deploy-init/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1006:22)
    at DeploymentsManager.runDeploy (/Users/clemsos/Dev/unlock/hardhat-deploy-init/node_modules/hardhat-deploy/src/DeploymentsManager.ts:844:5)
    at Environment._runTaskDefinition (/Users/clemsos/Dev/unlock/hardhat-deploy-init/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (/Users/clemsos/Dev/unlock/hardhat-deploy-init/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
```

many thanks !

**Comment by wighawag** [comment] 2021-06-11 09:18
hmm, could it be that you have 2 contract named "DiscountToken" ?

can you try specifying the fully qualified name

```js
    const dt = await deploy('DiscountToken', {
        from: owner,
        contract: "<path to file>:DiscountToken",
        log: true,
        args: [minter],
        proxy: {
            methodName: 'initialize',
            owner: proxyAdmin,
            proxyContract: 'OpenZeppelinTransparentProxy',
        }
    });
```

**Comment by clemsos** [comment] 2021-06-11 09:19
digging more, it seems to be a name conflict. 

From the devdocs, there are several function with the same name - inherited from `ERC20Detailed` and `ERC20Mintable`, plus the one at the top level of the contract.
 
```json
"initialize(address)": {
    "params": {
        "_minter": "A wallet with permissions to mint tokens and/or add other minters."
    }
},
"initialize(string,string,uint8)": {
    "details": "Sets the values for `name`, `symbol`, and `decimals`. All three of these values are immutable: they can only be set once during construction."
},
```

If I rename my function from `initialize` to `init` then the deployment works

**Comment by clemsos** [comment] 2021-06-11 09:22
thanks for the answer, just saw it as I was writing my comment. I just tried with adding the `contract` arg in `ProxyArgs` but the result still the same

**Comment by wighawag** [comment] 2021-06-17 05:10
@clemsos the fully qualified name is as follow `<relative path to file.sol>:<Contract Name>`
the relative path do not start with "./"

**Comment by wighawag** [comment] 2021-10-03 18:44
I close the issue for now, feel free to reopen if the issue is still relevant

**Closed by wighawag** 2021-10-03 18:44 UTC
