### ISSUE TITLE
`hardhat-deploy` doesn't work with `solidity-coverage`

### ISSUE THREAD

**Issue by lcswillems** [wighawag/hardhat-deploy#132] opened 2021-06-22 11:01 UTC
To reproduce:

1. Clone https://github.com/wighawag/template-ethereum-contracts
2. `yarn`
3. `yarn coverage`

And you should get this error:

![image](https://user-images.githubusercontent.com/5437552/122913620-f459ad80-d359-11eb-9bcc-549dfe2b2fd2.png)

**Comment by Dylan-Kerler** [comment] 2021-06-24 17:31
+1

**Comment by lcswillems** [comment] 2021-06-29 07:47
@wighawag Is it an issue on my side? Or is it an issue in hardhat-deploy?

**Comment by tzapu** [comment] 2021-07-02 09:32
same for me

**Comment by johnmaia** [comment] 2021-07-02 10:29
+1

**Comment by penandlim** [comment] 2021-07-07 01:47
This seems to have been introduced in `0.8.x`. Using `0.7.11` works for me.

**Comment by wighawag** [comment] 2021-07-07 07:37
Thanks all for reporting.

Sorry for the late reply, I am currently traveling with family and do not have much time on my laptop.

I had a look today though and the issue is that solidity-coverage create a new network object here: https://github.com/sc-forks/solidity-coverage/blob/3c0f3a5c7db26e82974873bbf61cf462072a7c6d/plugins/resources/nomiclabs.utils.js#L136-L141 overriding any modifications made by other plugins.

hardhat-deploy/solidity-coverage compatibility had a similar issue in the past for that same reason (see https://github.com/sc-forks/solidity-coverage/issues/624) and hardhat-deploy made a workaround for it at that time but newest hardhat-deploy version relies on the ability to add field to the network object, it thus also relies on accessing the network object at plugin import time and so the fix should in my opinion be in solidity-coverage. Instead of creating a new object, solidity-coverage could simply modify the existing `hre.network`  keeping any other addition from other plugins to it.

A replacement of these line https://github.com/sc-forks/solidity-coverage/blob/3c0f3a5c7db26e82974873bbf61cf462072a7c6d/plugins/resources/nomiclabs.utils.js#L136-L141

To these:

```
env.network.name = networkName;
env.network.config = networkConfig;
env.network.provider = provider;
env.network.isHardhatEVM = isHardhatEVM;
```

Should do it

What do you think @cgewecke ?

**Comment by GeekBerry** [comment] 2021-07-07 09:15
but what is the `env` ? how could i config it?

**Comment by lcswillems** [comment] 2021-07-07 11:00
@wighawag Thank you for the time you took to investigate!!

I hope @cgewecke will be able to modify solidity-coverage soon...

**Comment by tuler** [comment] 2021-07-10 06:33
> ```
> env.network.name = networkName;
> env.network.config = networkConfig;
> env.network.provider = provider;
> env.network.isHardhatEVM = isHardhatEVM;
> ```
> 
> Should do it

Tested and it works.

**Comment by GeekBerry** [comment] 2021-07-12 02:51
> > ```
> > env.network.name = networkName;
> > env.network.config = networkConfig;
> > env.network.provider = provider;
> > env.network.isHardhatEVM = isHardhatEVM;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Should do it
> 
> Tested and it works.

em~, but what is `env` ? `process.env` or `require('hardhat').network.isHardhatEVM`?

**Comment by lcswillems** [comment] 2021-07-12 07:17
@GeekBerry If you look at the code wighawag pointed to, you will understand: https://github.com/sc-forks/solidity-coverage/blob/3c0f3a5c7db26e82974873bbf61cf462072a7c6d/plugins/resources/nomiclabs.utils.js#L136-L141

**Comment by GeekBerry** [comment] 2021-07-12 08:13
> @GeekBerry If you look at the code wighawag pointed to, you will understand: https://github.com/sc-forks/solidity-coverage/blob/3c0f3a5c7db26e82974873bbf61cf462072a7c6d/plugins/resources/nomiclabs.utils.js#L136-L141

I hack in `node_modules/solidity-coverage/plugins/resources/nomiclabs.utils.js` and change line 136 to
```js
env.network = Object.assign({
    name: networkName,
    config: networkConfig,
    provider: provider,
    isHardhatEVM: isHardhatEVM,
}, env.network);
```
then run coverage successful.

I guess solidity-coverage author might fix this issue next version.

**Comment by notsegfault** [comment] 2021-08-24 00:01
+1

**Comment by wighawag** [comment] 2021-08-24 07:44
Hey all, the issue is on the solidity-coverage side, I ll close the issue as hardhat-deploy cannot do much.
In my template, I patch solidity-coverage with `patch-package` and have it working, see : https://github.com/wighawag/template-ethereum-contracts/blob/main/patches/solidity-coverage%2B0.7.16.patch

There is this PR that fixes it in solidity-coverage : https://github.com/sc-forks/solidity-coverage/pull/647

**Closed by wighawag** 2021-08-24 07:44 UTC
