### ISSUE TITLE
unexpected result if you use deterministic deployment with proxy:true

### ISSUE THREAD

**Issue by tzapu** [wighawag/hardhat-deploy#129] opened 2021-06-18 11:00 UTC
using this snippet 
```
  const deployer = await deterministic(deploymentName, {
    from: owner,
    args: [],
    log: true,
    salt: salt,
    proxy: {
      proxyContract: "OptimizedTransparentProxy"
    }
  });
```
i get a deterministic address for the implementation while I would expect the deterministic bit to apply to the proxy as that will be the entry point. 
is this intended?

thanks you very much

**Comment by wighawag** [comment] 2021-06-18 11:17
the field is `deterministicDeployment` not salt, it can be a boolean or a bytes32 salt

**Comment by wighawag** [comment] 2021-06-18 11:33
Thanks for the report @tzapu 
it is indeed not intended
The issue is that TransparentProxy have an intermediate proxy as owner, the ProxyAdmin. the onwer of the proxy is given in the constructor.
currently hardhat-deploy always deploy the ProxyAdmin non-deterministcally, this result in the proxy being also non-deterministic

I ll fix that by making ProxyAdmin deterministic if not already deployed

**Comment by wighawag** [comment] 2021-06-18 11:38
fixed in 0.8.7

**Comment by tzapu** [comment] 2021-06-18 12:13
gave it a spin, thank you. 
seems to mostly work, but now when i re-run deploy, instead of 'reusing contract...' i just get `Error: already deployed on same deterministic address: `
maybe it s something particular to my setup but figured i d report it anyway

**Comment by wighawag** [comment] 2021-06-18 14:58
This means that you deployed a proxy at that address in the past but that you deleted the corresponding deployment file

The reason it hard fails is that proxy have identical code and so if they use the same owner, every proxy will always be one and this is probably not what you want.

If you need a new proxy with same owner, you ll have to use a different salt.

I could add an option to force the reconstruction of the proxy though

**Comment by marcelomorgado** [comment] 2021-09-28 16:21
> fixed in 0.8.7

Hi @wighawag are you sure that it was fixed?

I've created one deterministic script for each contract (all using `OpenZeppelinTransparentProxy`) and since they have some bi-directional relationships, I'm getting their create2 addresses to use for initialization calls.
What is happening here is that the `deterministic` function is returning the implementation address instead of the proxy address.

Example:

```typescript
import {HardhatRuntimeEnvironment} from 'hardhat/types'
import {DeployFunction} from 'hardhat-deploy/types'

const func: DeployFunction = async (hre: HardhatRuntimeEnvironment) => {
  const {getNamedAccounts, deployments} = hre
  const {execute, deterministic} = deployments
  const {deployer} = await getNamedAccounts()

  const {deploy} = await deterministic('ContractA', {
    from: deployer,
    log: true,
    proxy: {
      proxyContract: 'OpenZeppelinTransparentProxy',
    },
  })
  await deploy()

  // contractB_address is returning the implementation address instead of proxy address
  const {address: contractB_address} = await deterministic('ContractB', {
    from: deployer,
    log: true,
    proxy: {
      proxyContract: 'OpenZeppelinTransparentProxy',
    },
  })

  await execute('ContractA', {from: deployer, log: true}, 'initialize', contractB_address)
}

export default func
```
Note: I'm using `hardhat-deploy` 0.9.1

**Comment by wighawag** [comment] 2021-09-28 17:09
Thanks @marcelomorgado  for your report
 it does sounds like a different issue. what made you think the issue is the same ?

**Comment by marcelomorgado** [comment] 2021-09-28 17:13
Hmmm I've thought that the issue open comment is about the same issue
> ... i get a deterministic address for the implementation while I would expect the deterministic bit to apply to the proxy as that will be the entry point. ...

If you prefer I can open another issue

**Comment by wighawag** [comment] 2021-09-28 20:21
OK, I see, for me the issue is different in that for the original creator, the issue was that the proxy was not deployment deterministically. and this got fixed

Your issue is that the function that `deterministic` function return you the deterministic address of the implementation instead of the expect proxy address

I think it is better to create a new issue as the current one is actually still open because I could improve the error as mentioned in this comment : https://github.com/wighawag/hardhat-deploy/issues/129#issuecomment-864099083

**Comment by marcelomorgado** [comment] 2021-09-29 14:17
Thanks, sure!
Extracted to: https://github.com/wighawag/hardhat-deploy/issues/199#issue-1011023910

**Comment by wighawag** [comment] 2021-10-03 18:45
I close this one for now and as my comment mention here : https://github.com/wighawag/hardhat-deploy/issues/129#issuecomment-864099083
I could potentially do something along these lines:
>  I could add an option to force the reconstruction of the proxy though

But I ll leave that for another issue if this become requested

**Closed by wighawag** 2021-10-03 18:45 UTC
